//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Unknown Error Occured.
        /// </summary>
        internal static string _100_DESCRIPTION {
            get {
                return ResourceManager.GetString("100_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Debug Through Code To Solve The Issue.
        /// </summary>
        internal static string _100_SOLUTION {
            get {
                return ResourceManager.GetString("100_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not Authorised To Proceed.
        /// </summary>
        internal static string _10001_DESCRIPTION {
            get {
                return ResourceManager.GetString("10001_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Verify With Correct User Credentials.
        /// </summary>
        internal static string _10001_SOLUTION {
            get {
                return ResourceManager.GetString("10001_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not Found Or User Is Not A Registered User.
        /// </summary>
        internal static string _10002_DESCRIPTION {
            get {
                return ResourceManager.GetString("10002_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login With Existing User or Regester A New User.
        /// </summary>
        internal static string _10002_SOLUTION {
            get {
                return ResourceManager.GetString("10002_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Validate Request.
        /// </summary>
        internal static string _101_DESCRIPTION {
            get {
                return ResourceManager.GetString("101_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Verify The Request And Try Again With Proper Inputs.
        /// </summary>
        internal static string _101_SOLUTION {
            get {
                return ResourceManager.GetString("101_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100:Unknown Error.
        /// </summary>
        internal static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001:Authentication Error.
        /// </summary>
        internal static string ERR_USER_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10002:Not Found.
        /// </summary>
        internal static string ERR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101:Validation Failed.
        /// </summary>
        internal static string ERR_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_FAILED", resourceCulture);
            }
        }
    }
}
