//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Common {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Unknown Error Occured.
        /// </summary>
        internal static string _100_DESCRIPTION {
            get {
                return ResourceManager.GetString("100_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Debug Through Code To Solve The Issue.
        /// </summary>
        internal static string _100_SOLUTION {
            get {
                return ResourceManager.GetString("100_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not Authorised To Proceed.
        /// </summary>
        internal static string _10001_DESCRIPTION {
            get {
                return ResourceManager.GetString("10001_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Verify With Correct User Credentials.
        /// </summary>
        internal static string _10001_SOLUTION {
            get {
                return ResourceManager.GetString("10001_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not Found Or User Is Not A Registered User.
        /// </summary>
        internal static string _10002_DESCRIPTION {
            get {
                return ResourceManager.GetString("10002_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login With Existing User or Regester A New User.
        /// </summary>
        internal static string _10002_SOLUTION {
            get {
                return ResourceManager.GetString("10002_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Not Allowed To Access The Content.
        /// </summary>
        internal static string _10003_DESCRIPTION {
            get {
                return ResourceManager.GetString("10003_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again With User With Appropiate Permissions.
        /// </summary>
        internal static string _10003_SOLUTION {
            get {
                return ResourceManager.GetString("10003_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists with this username or email.
        /// </summary>
        internal static string _10004_DESCRIPTION {
            get {
                return ResourceManager.GetString("10004_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an username or email that is not registered yet.
        /// </summary>
        internal static string _10004_SOLUTION {
            get {
                return ResourceManager.GetString("10004_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Validate Request.
        /// </summary>
        internal static string _101_DESCRIPTION {
            get {
                return ResourceManager.GetString("101_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Verify The Request And Try Again With Proper Inputs.
        /// </summary>
        internal static string _101_SOLUTION {
            get {
                return ResourceManager.GetString("101_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Is Not Found Or Group Is Not Yet Created.
        /// </summary>
        internal static string _20001_DESCRIPTION {
            get {
                return ResourceManager.GetString("20001_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Create A New Group Or Enter An Existing Group.
        /// </summary>
        internal static string _20001_SOLUTION {
            get {
                return ResourceManager.GetString("20001_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group already exists with this name.
        /// </summary>
        internal static string _20002_DESCRIPTION {
            get {
                return ResourceManager.GetString("20002_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an group name that is not yet taken.
        /// </summary>
        internal static string _20002_SOLUTION {
            get {
                return ResourceManager.GetString("20002_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense is not found or expense is not yet created.
        /// </summary>
        internal static string _30001_DESCRIPTION {
            get {
                return ResourceManager.GetString("30001_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a new expense or enter an existing expense.
        /// </summary>
        internal static string _30001_SOLUTION {
            get {
                return ResourceManager.GetString("30001_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30001:Not Found.
        /// </summary>
        internal static string ERR_EXPENSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_EXPENSE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20002:Already Exists.
        /// </summary>
        internal static string ERR_GROUP_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERR_GROUP_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20001:Not Found.
        /// </summary>
        internal static string ERR_GROUP_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_GROUP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100:Unknown Error.
        /// </summary>
        internal static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10004:Already Exists.
        /// </summary>
        internal static string ERR_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERR_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10003:User Forbidden.
        /// </summary>
        internal static string ERR_USER_FORBIDDEN {
            get {
                return ResourceManager.GetString("ERR_USER_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001:Authentication Error.
        /// </summary>
        internal static string ERR_USER_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10002:Not Found.
        /// </summary>
        internal static string ERR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101:Validation Failed.
        /// </summary>
        internal static string ERR_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_FAILED", resourceCulture);
            }
        }
    }
}
